baseURL = "https://www.s-brands.pl"
defaultContentLanguage = "pl"
languageCode = "en-us"
summaryLength = "10"
theme = "icelab-hugo"
title = "agencjawroclawska"
[languages.en]
title = "My blog"
weight = 2
[languages.pl]
title = "Mon blogue"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
author = "agencjawroclawska.pl"
contact_form_action = "#"
description = "This is meta description"
footer_content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus sint magnam quia doloremque."
home = "Home"
logo = "images/logo.png"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.js]]
URL = "plugins/plugins.js"
[permalinks]
"/" = "/:slug/"
nasze-marki = "/:slug/"
page = "/:slug/"
posts = "/:slug/"
